### ISSUE TITLE
again - browsers unusable on RPi model < 4B, reason discovered

### ISSUE THREAD

**Issue by sgalke** [raspberrypi/bookworm-feedback#105]
just the same symptom as described in #89  again yesterday!
browsers freeze the machine after a few seconds...
reason:   wayland  selected in raspi-config dialog on models < 4B!

**Comment by sgalke** [comment]
.. vnc connection seems to trigger also  browser freezing the system.

**Comment by popcornmix** [comment]
> reason: wayland selected in raspi-config dialog on models < 4B!

Are you saying you have manually enabled wayland on a Pi3 (or lower)?
Or are you saying wayland was enabled automatically? (it shouldn't be).

We've not enabled wayland by default on those devices because the memory consumption is too high.
It wouldn't be surprising that browsers are not usable in a low memory situation.

**Comment by sgalke** [comment]
manually enabled wayland in raspi-config

**Comment by lurch** [comment]
Running Wayland isn't officially recommended (yet) on a Pi3 or below, so closing this issue.
