### ISSUE TITLE
Having trouble getting ibus input method editor to work in Wayland

### ISSUE THREAD

**Issue by JinShil** [raspberrypi/bookworm-feedback#127]
I'm testing ibus with ibus-hangul (Korean input method editor).  It works fine in X windows, but does not work in Wayland.

I tried installing ibus-wayland, but that didn't seem to do anything automatically.  I'm not sure if additional configuration is required.

Anyway the typical ibus configuration does not work in Wayland, but works fine in X.

**Comment by ghollingworth** [comment]
I'm guessing this is because the ibus-wayland package requires that the Wayland compositor support the "input-method-unstable-v1" protocol.

I think this is really either a Wayfire or an ibus-wayland issue and should be reported there.  Unless you can find a reason why it is not working through XWayland
