### ISSUE TITLE
pipewire is not installed with pi os lite

### ISSUE THREAD

**Issue by byzantic** [raspberrypi/bookworm-feedback#134]
I have the same problems reported in #24. However, while trying (and failing) to set up a codec zero  on a Pi Zero 2 W, I tried a clean install of Pi OS lite (64 bit, bookworm, dated 2023-10-27).

I noticed that there was no audio subsystem installed by default, neither pipewire, nor pulsaudio. It was fairly straightforward to install the pipewire subsystem using `sudo apt install pipewire`, which seemed to install correctly, but there seems to be no way to set up a default audio card - `raspi-config` reported no audio card.

Since `pipewire` is also used for media routing (video and camera), and some common Zero 2 W usecases might involve a camera, should pipewire be pre-installed? If not then I think this is another area where the documentation needs to be expanded.

**Comment by lurch** [comment]
I've done some extensive testing, and after a couple of dead-ends (caused by partially-dead hardware) I've verified that the Codec Zero board works fine in Bookworm (both Desktop and Lite versions), tested on Pi 5 and Pi Zero 2 W.

Some things to watch out for:
* the 3.5mm socket on the CodecZero board is (only) a microphone-input, NOT a headphone-output
* if you're very unlucky, you might have an unprogrammed board, which can be fixed using [these instructions](https://www.raspberrypi.com/documentation/accessories/audio.html#updating-your-firmware)
* if you're using Raspberry Pi OS Lite you need to use the `raspi-config` [System -> Audio](https://www.raspberrypi.com/documentation/computers/configuration.html#list-of-options) option to select the Codec Zero card
* you need to follow the `alsactl restore` [instructions](https://www.raspberrypi.com/documentation/accessories/audio.html#extra-codec-zero-configuration) - if `Codec_Zero_OnboardMIC_record_and_SPK_playback.state` doesn't work, try using `Codec_Zero_Playback_only.state`. Note that you may see a long list of errors ("failed to import hw" or "No state is present for card"), but these are just harmless warnings.
* you may need to use the `alsamixer` command to adjust the volume of the appropriate output channel
* neither `pipewire` nor `pulseaudio` need to be installed on the Lite image for audio output - I was using a small speaker wired up to the screw-terminals on the Codec Zero board and testing with `aplay /usr/share/sounds/alsa/Front_Center.wav`

**Comment by haricane8133** [comment]
Why isn't pipewire pre-installed in the lite version?
