### ISSUE TITLE
Running DRM graphics apps leads to broken console text on app exit

### ISSUE THREAD

**Issue by qrp73** [raspberrypi/bookworm-feedback#141]
### Steps to reproduce 1:

1) Compile and install glmark2-drm:
```
sudo apt install libjpeg-dev libdrm-dev libgbm-dev libudev-dev meson ninja-build
git clone https://github.com/glmark2/glmark2.git
cd glmark2
meson setup build -Dflavors=drm-gl,drm-glesv2
ninja -C build
sudo ninja -C build install
```
2) Switch to a virtual terminal with pressing Ctrl+Alt+F1
3) execute: ```glmark2-drm```
4) wait until test will be finished

Expected result: display text mode console text is restored and user prompted for a new command

Actual result: display text mode is restored, but console text is broken (can be restored by pressing any key)

Note: virtual terminal should contains some output and the prompt needs to be at the end of screen. If ```clear``` command is executed before test it restores part of text. Looks like broken text happens when text scroll happens during app run.

### Steps to reproduce 2:

1) Compile and install kmscube drm demo:
```
sudo apt install meson ninja-build
git clone https://gitlab.freedesktop.org/mesa/kmscube.git
cd kmscube
mkdir build
meson setup build/
cd build/
ninja
```
2) Switch to a virtual terminal with pressing Ctrl+Alt+F1
3) execute:
```
cd kmscube/build
./kmscube
```
4) It should show rotating cube, then press Enter

Expected result: display text mode console text is restored and user prompted for a new command

Actual result: black screen (can be restored by pressing Ctrl+Alt+F2 and then back Ctrl+Alt+F1)

**Comment by qrp73** [comment]
not relevant anymore

**Comment by 6by9** [comment]
Whilst Wayfire relinquishes DRM Master when you Ctrl-Alt-Fx to a different terminal, it keeps the /dev/dri/cardN file descriptor open.
The kernel code to restore the emulated framebuffer is `drm_fb_helper_lastclose`, which is run when the last file handle on the node is closed. Due to Wayfire still having a handle, it isn't run, and we end up with the connector enabled, but no planes on it.

If you run from the console without Wayfire running, it behaves as expected.

This needs checking through as to how exactly Wayfire behaves when you Ctrl-Alt-Fx to a different console.
