### ISSUE TITLE
RASPI Touchscreen 7'' rotate screen

### ISSUE THREAD

**Issue by awiltschek** [raspberrypi/bookworm-feedback#154]
i have now tried this out on several versions of raspi os and adding  lcd_rotate=2 to the config.txt works for the first boot sequence (some pages) and during the boot the screen shortly gets blank then the rest of the boot sequence is done again in the wrong orientation.
Which strange feature shall this be when the first part of the boot sequence it works and the switch back.
I was now searching for appropriate solutions for command line (not GUI ! i use Klipperscreen which is after the switch back although in the wrong orientation) but could not find any usefull solution which worked.

As i sayed lcd_rotates=2 works for the first view boot pages then it switches back. Nonsense

**Comment by pelwell** [comment]
> i have now tried this out on several versions of raspi os

Did you get the same behaviour on Bullseye?

**Comment by awiltschek** [comment]
yes same - actual i switched back to bullseye because KlipperScreen was running more smooth and i didnt have the bug received with crowsnest.

**Comment by lurch** [comment]
This is because the very early bootscreens use the legacy/firmware graphics stack, and it's only the legacy graphics that respond to the `lcd_rotate` option in `config.txt` - see https://www.raspberrypi.com/documentation/computers/legacy_config_txt.html

On Bookworm, once the Linux kernel properly kicks in it then switches to the DRM / KMS graphics stack, and to rotate the LCD in that environment, see the instructions at https://www.raspberrypi.com/documentation/accessories/display.html#changing-the-screen-orientation and https://www.raspberrypi.com/documentation/computers/configuration.html#setting-your-displays-resolution-and-rotation
