### ISSUE TITLE
adb

### ISSUE THREAD

**Issue by spookyfirehorse** [raspberrypi/bookworm-feedback#261]
Hi and Hello

pi bookworm on pi zero W  arm1176jzf-s

adb over apt installled 

in deutsch üngültiger maschienen befehl 

error massage may in english unknown machincode 

i also tried dpkg-buildpackage but ther is also some error

thanks for your great work 

and sorry for my english

spooky

**Comment by XECDesign** [comment]
At first I thought it was because our version of android-platform-tools was a problem. I've pulled it from the armhf repo, but the issue is still there with Raspbian's build, but this time in android-libboringssl.

I believe the issue should be reported [here](https://bugs.launchpad.net/raspbian/+bugs) instead.

**Comment by longo92-vrmedia** [comment]
Any news? i have the same issue using gdb it seems on: /usr/lib/arm-linux-gnueabihf/android/libcrypto.so.0


![image](https://github.com/user-attachments/assets/985180c7-cf57-4785-b320-493e0a0c50aa)

**Comment by 0awe** [comment]
In case anyone else stumbles across this issue, it has also been logged [here](https://bugs.launchpad.net/raspbian/+bug/2091145).
